# 多个训练配置
default0: 
  n_envs: 30
  policy: MultiInputPolicy
  model:
    learning_rate: 0.0003
    n_steps: 2048
    batch_size: 64
    n_epochs: 10
    gamma: 0.99
    gae_lambda: 0.95
    clip_range: 0.2
    ent_coef: 0.0
    vf_coef: 0.5
    max_grad_norm: 0.5
  total_timesteps: 5000000
  save_freq: 1000000
  eval_freq: 1000000
default_1: 
  n_envs: 32
  policy: 'MultiInputPolicy'
  model:
    n_steps: 1024
    gamma: 0.999
  total_timesteps: 1000000
  save_freq: 10000
  eval_freq: 10000
default_2: 
  n_envs: 24
  policy: 'MultiInputPolicy'
  model:
    n_steps: 1024
    gamma: 0.999
  total_timesteps: 10000000
  save_freq: 10000
  eval_freq: 10000
default_3: 
  n_envs: 32
  policy: 'MultiInputPolicy'
  model:
    n_steps: 1024
    gamma: 0.999
  total_timesteps: 2000000
  save_freq: 10000
  eval_freq: 10000
default_4: 
  n_envs: 32
  policy: 'MultiInputPolicy'
  model:
    n_steps: 2048
    gamma: 0.996
  total_timesteps: 3000000
  save_freq: 10000
  eval_freq: 10000
default_5: 
  n_envs: 32
  policy: 'MultiInputPolicy'
  model:
    n_steps: 2048
    gamma: 0.996
  total_timesteps: 3000000
  save_freq: 10000
  eval_freq: 10000